Ilay reset filters icon
smg-automotive/components-pkg pull request #578
Opened 2023-04-12 12:41 UTC by ilay149

References [link the ticket here]

## Motivation and context

[Describe the problem we're solving and lay out the solution]

## Before

[Describe the current behavior and / or add a screenshot of the current state]

## After

[Describe the new behavior and / or add a screenshot of the new state]

## How to test

[Add a deep link and instructions how to verify the new behavior]

2023-04-13 13:36 UTC, talamcol requested changes
there are unrelated changes in this PR. Please double check your commit history and try to resolve it. Let me know if you need help with that

2023-04-13 13:40 UTC, talamcol commented on src/components/icons/ResetFiltersIcon.tsx
> +export const ResetFiltersIcon = createIcon({
It does not necessarily have to do with filters. Could be used in other places. Let's call it `ResetIcon`. Or align with Figma and call it `RotateIcon`

2023-04-18 06:31 UTC, talamcol approved these changes

2023-04-18 06:32 UTC, lkappeler approved these changes
Thanks

2023-04-18 06:35 UTC, merged