Feat add column layouts
smg-automotive/components-pkg pull request #733
Opened 2023-09-12 14:16 UTC by mmataja

References [[link the ticket here](https://autoricardo.atlassian.net/browse/DM-2027)]

## Motivation and context
To enable 3 layout column for our advanced filter group without affecting too much of the other components, current implementations or introducing new one (which is still a valid option). Option for checkbox Filter group was added with `numberOfColumns`, depending on that number `items` are split equally between columns that we want.

## Before
No column layout option.

## After
![image](https://github.com/smg-automotive/components-pkg/assets/28811793/012f2b3d-4ca1-4bac-9a1b-a4e16f3d8bd2)
![image](https://github.com/smg-automotive/components-pkg/assets/28811793/4ecc96e7-eb27-438a-8362-d92964f93250)

## How to test

2023-09-13 11:11 UTC, talamcol requested changes
I don't think we need JS here. This can be achieved using CSS columns: https://developer.mozilla.org/en-US/docs/Web/CSS/columns

it does all the distribution automatically, you can style the border etc.

2023-09-14 06:57 UTC, talamcol approved these changes
very simple. Love it!

2023-09-14 06:57 UTC, talamcol commented on src/components/checkboxFilter/index.tsx
> +  numberOfColumns?: number;
to avoid misunderstandings you might want to go with:

```suggestion
  numberOfColumnsOnDesktop?: number;
```

2023-09-14 07:02 UTC, talamcol approved these changes

2023-09-14 07:02 UTC, talamcol commented on src/components/checkboxFilter/index.tsx
>        {items.map((item) => {
```suggestion
      {items.map((item,index) => {
```

2023-09-14 07:02 UTC, talamcol commented on src/components/checkboxFilter/index.tsx
> +          <Box key={item.key} width="full" marginBottom="2xl">
```suggestion
          <Box key={item.key} width="full" marginBottom={index === items.length-1 ? 0 : "2xl"}>
```

2023-09-14 07:37 UTC, mmataja commented on src/components/checkboxFilter/index.tsx
> +          <Box key={item.key} width="full" marginBottom="2xl">
Not going to work :(

2023-09-14 07:51 UTC, merged